# Generated by Django 3.2.5 on 2023-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='rollno',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
